services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://ettijohn.42web.io
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ""   # Change to your Render MySQL service name
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: portfolio_db
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
